# Generated by Django 3.2.4 on 2021-07-10 11:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groot', '0004_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='participants_history',
            field=models.ManyToManyField(blank=True, related_name='past_rooms_of_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
