CALL_CONNECTED = "CALL_CONNECTED"
ICE_CANDIDATE = 'ICE_CANDIDATE'
OFFER = 'OFFER'
ANSWER = 'ANSWER'
PARTICIPANT_LEFT = 'PARTICIPANT_LEFT'

specific_user_messages = [
    ICE_CANDIDATE,
    OFFER,
    ANSWER
]

VIDEO_OFF = 'VIDEO_OFF'
AUDIO_OFF = 'AUDIO_OFF'
