version: '3.8'

services:
    db:
        restart: always
        build: ./postgresql
        container_name: groot_db
        env_file: 
            - ./postgresql/database.env
        expose: 
            - 5432
        volumes: 
            - database:/var/lib/postgresql/data/
        networks:
            - groot_network
    
    redis:
        restart: always
        build: ./redis
        container_name: groot_redis
        expose:
            - 6379
        networks:
            - groot_network
    
    web:
        restart: always
        build: ./django
        container_name: groot_web
        command: sh -c "python manage.py runserver 0.0.0.0:8000"
        volumes: 
            - ./django/code:/code/
            - ./static/:/static/
            - ./media/:/media/
        expose:
            - 8000
        ports:
            - "60000:8000"
        depends_on:
            - db
            - redis
        networks:
            groot_network:

volumes: 
    database:

networks:
    groot_network: