version: '3.8'

services:
    db:
        restart: always
        build: ../groot-backend/postgresql
        container_name: groot_db
        env_file: 
            - ../groot-backend/postgresql/database.env
        expose: 
            - 5432
        volumes: 
            - database:/var/lib/postgresql/data/
        networks:
            - groot_network
    
    redis:
        restart: always
        build: ../groot-backend/redis
        container_name: groot_redis
        expose:
            - 6379
        networks:
            - groot_network
    
    web:
        restart: always
        build: ../groot-backend/django
        container_name: groot_web
        command: sh -c "python manage.py collectstatic --no-input  && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
        volumes: 
            - ../groot-backend/static/:/static/
            - ../groot-backend/media/:/media/
        expose:
            - 8000
        depends_on:
            - db
            - redis
        networks:
            groot_network:
    
    frontend:
        build: ../groot-frontend
        container_name: groot_frontend
        command: sh -c "yarn build"
        volumes: 
            - frontend_build:/groot/build/
        expose:
            - 3000
        depends_on: 
            - web
        networks: 
            groot_network:

    reverse_proxy:
        build:
            context: ../nginx
        restart: always
        container_name: groot_reverse_proxy
        expose:
            - 80
            - 443
        ports:
            # - "80:80"
            # - "443:443"
            - "50069:80"
            - "51069:443"
        volumes:
            - ../nginx/ssl/:/etc/nginx/ssl/
            - static:/groot_static/
            - media:/groot_media/
            - frontend_build:/groot_frontend/
        depends_on:
            - web
            - frontend
        networks:
            - groot_network

volumes: 
    database:

    frontend_build:

    static:

    media:

networks:
    groot_network: